[project]
name = "analisismercado"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.5.3",
    "joblib>=1.5.3",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.9",
    "mlflow>=3.13.0",
    "nbformat>=5.10.4",
    "numba>=0.65.1",
    "pandas>=2.3.3",
    "plotly>=6.8.0",
    "polars>=1.41.2",
    "pytest>=9.0.3",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "scikit-learn>=1.7.2",
    "shap>=0.49.1",
    "ta>=0.11.0",
    "tensorflow>=2.21.0",
    "vectorbt>=0.28.2",
    "xgboost>=3.2.0",
    "yfinance>=1.4.1",
]
