import os
import sys
import pandas as pd
import duckdb
from ta.momentum import RSIIndicator
from ta.trend import MACD, SMAIndicator
from ta.volatility import BollingerBands

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if BASE_DIR not in sys.path:
    sys.path.append(BASE_DIR)

from src.config import (
    DATA_RAW_DIR, DATA_PROCESSED_DIR, TARGET_COL, EXPECTED_RETURN_COL,
    FEE_RATE, SLIPPAGE, DUCKDB_PATH, PARQUET_DIR
)
from src.logger import get_logger

logger = get_logger(__name__)

def add_technical_indicators(df):
    """
    Adds RSI, MACD, Moving Averages and Bollinger Bands to the dataframe.
    """
    df['RSI'] = RSIIndicator(close=df['Close'], window=14).rsi()
    macd = MACD(close=df['Close'])
    df['MACD'] = macd.macd()
    df['MACD_Signal'] = macd.macd_signal()
    df['SMA_20'] = SMAIndicator(close=df['Close'], window=20).sma_indicator()
    df['SMA_50'] = SMAIndicator(close=df['Close'], window=50).sma_indicator()
    
    bb = BollingerBands(close=df['Close'], window=20, window_dev=2)
    df['BB_High'] = bb.bollinger_hband()
    df['BB_Low'] = bb.bollinger_lband()
    
    return df

def run_feature_engineering():
    """
    Executes Phase 2: Feature Engineering and Realistic Target creation.
    """
    os.makedirs(DATA_PROCESSED_DIR, exist_ok=True)
    
    # 1. Load Data from DuckDB
    logger.info("Loading base data from DuckDB Parquet views...")
    
    con = duckdb.connect(database=DUCKDB_PATH, read_only=True)
    
    klines_path = os.path.join(PARQUET_DIR, "klines", "*.parquet")
    funding_path = os.path.join(PARQUET_DIR, "fundingRate", "*.parquet")
    oi_path = os.path.join(PARQUET_DIR, "openInterestHist", "*.parquet")
    
    # We query the parquet files directly to avoid dependency on persistent views
    query = f"""
        WITH klines AS (SELECT Date, open, high, low, close, volume FROM '{klines_path}'),
             funding AS (SELECT Date, funding_rate FROM '{funding_path}'),
             oi AS (SELECT Date, sum_open_interest, sum_open_interest_value FROM '{oi_path}')
        SELECT 
            k.Date,
            k.open as Open,
            k.high as High,
            k.low as Low,
            k.close as Close,
            k.volume as Volume,
            f.funding_rate as Funding_Rate,
            o.sum_open_interest as Open_Interest,
            o.sum_open_interest_value as Open_Interest_Value
        FROM klines k
        LEFT JOIN funding f ON DATE_TRUNC('day', k.Date) = DATE_TRUNC('day', f.Date)
        LEFT JOIN oi o ON DATE_TRUNC('day', k.Date) = DATE_TRUNC('day', o.Date)
        ORDER BY k.Date
    """
    
    try:
        df_btc = con.execute(query).df()
    except Exception as e:
        logger.error(f"Failed to query DuckDB: {e}. Ensure data_loader.py has run successfully.")
        raise
    finally:
        con.close()

    df_btc['Date'] = pd.to_datetime(df_btc['Date'])
    df_btc = df_btc.set_index('Date')
    
    # Drop duplicates if any generated by joins
    df_btc = df_btc[~df_btc.index.duplicated(keep='first')]
    
    df_btc = add_technical_indicators(df_btc)
    
    # 2. Merge Exogenous Variables
    vix_path = os.path.join(DATA_RAW_DIR, "VIX_raw.csv")
    if os.path.exists(vix_path):
        df_vix = pd.read_csv(vix_path, index_col='Date', parse_dates=True)
        df_btc['VIX_Close'] = df_vix['Close']
    else:
        logger.warning("VIX data not found.")

    dxy_path = os.path.join(DATA_RAW_DIR, "DX_Y_NYB_raw.csv")
    if os.path.exists(dxy_path):
        df_dxy = pd.read_csv(dxy_path, index_col='Date', parse_dates=True)
        df_btc['DXY_Close'] = df_dxy['Close']
    else:
        logger.warning("DXY data not found.")

    fng_path = os.path.join(DATA_RAW_DIR, "fear_and_greed.csv")
    if os.path.exists(fng_path):
        df_fng = pd.read_csv(fng_path, index_col='Date', parse_dates=True)
        df_btc['Fear_Greed_Value'] = df_fng['value']
    else:
        logger.warning("Fear & Greed data not found.")
        
    cols_to_ffill = [col for col in ['VIX_Close', 'DXY_Close', 'Fear_Greed_Value', 'Funding_Rate', 'Open_Interest', 'Open_Interest_Value'] if col in df_btc.columns]
    df_btc[cols_to_ffill] = df_btc[cols_to_ffill].ffill()
    # For Funding rate, missing values before 2020 should be filled with 0 (neutral funding)
    if 'Funding_Rate' in df_btc.columns:
        df_btc['Funding_Rate'] = df_btc['Funding_Rate'].fillna(0.0)

    # 3. Create Realistic Target
    df_btc['Close_Tomorrow'] = df_btc['Close'].shift(-1)
    expected_return = (df_btc['Close_Tomorrow'] / df_btc['Close']) - 1.0
    threshold = (FEE_RATE * 2) + SLIPPAGE
    
    df_btc[TARGET_COL] = (expected_return > threshold).astype(int)
    df_btc[EXPECTED_RETURN_COL] = expected_return
    
    # 4. Clean up - CRITICAL: Data Leakage Prevention!
    df_btc = df_btc.drop(columns=['Close_Tomorrow'])
    df_btc = df_btc.dropna()
    
    output_path = os.path.join(DATA_PROCESSED_DIR, "final_features.csv")
    df_btc.to_csv(output_path)
    
    logger.info("Phase 2: Feature Engineering completed successfully.")
    logger.info(f"Dataset shape: {df_btc.shape}")
    logger.info(f"Target distribution:\n{df_btc[TARGET_COL].value_counts(normalize=True)}")
    logger.info(f"Saved processed features to {output_path}")

if __name__ == "__main__":
    run_feature_engineering()
